<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Cabang_toko_model extends CI_Model
{

    public $table = 'cabang_toko';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('ct.id,ct.id_toko,ct.id_cabang,t.nama_toko');
        $this->datatables->from('cabang_toko as ct');
        //add this line for join
        $this->datatables->join('toko as t', 't.id = ct.id_cabang','left');
        $this->datatables->add_column('action', 
        anchor(site_url('outlet/cabang_toko/delete/$1'),'<span class="btn btn-danger btn-xs">Hapus</span>','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // datatables
    function json_produksi() {
        $this->datatables->select('ct.id,ct.id_toko,ct.id_cabang,t.nama_toko');
        $this->datatables->from('cabang_toko as ct');
        //add this line for join
        $this->datatables->join('toko as t', 't.id = ct.id_cabang','left');
        $this->datatables->add_column('action', 
        anchor(site_url('produksi/cabang_toko/delete/$1'),'<span class="btn btn-danger btn-xs">Hapus</span>','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function is_pusat($id_toko) {
        $this->db->where('id_toko', $id_toko);
        $row = $this->db->get($this->table)->row();
        if(!empty($row)){
            return 1;
        }else{
            return 0;
        }
    }
    function get_by_id_toko($id_toko = '')
    {
        $this->db->select('*');
        $this->db->from('cabang_toko as ct');
        $this->db->join('toko as t', 't.id = ct.id_cabang', 'left');
        $this->db->where('ct.id_toko', $id_toko);
        return $this->db->get()->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
    	$this->db->or_like('id_toko', $q);
    	$this->db->or_like('id_cabang', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
    	$this->db->or_like('id_toko', $q);
    	$this->db->or_like('id_cabang', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Cabang_toko_model.php */
/* Location: ./application/models/Cabang_toko_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-10-17 03:41:30 */
/* http://harviacode.com */