<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Akun_iklan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Akun_iklan_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('akun_iklan/akun_iklan_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Akun_iklan_model->json();
    }

    public function read($id) 
    {
        $row = $this->Akun_iklan_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'id_group' => $row->id_group,
		'akun' => $row->akun,
	    );
            $this->load->view('akun_iklan/akun_iklan_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('akun_iklan'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('akun_iklan/create_action'),
	    'id' => set_value('id'),
	    'id_group' => set_value('id_group'),
	    'akun' => set_value('akun'),
	);
        $this->load->view('akun_iklan/akun_iklan_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_group' => $this->input->post('id_group',TRUE),
		'akun' => $this->input->post('akun',TRUE),
	    );

            $this->Akun_iklan_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('akun_iklan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Akun_iklan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('akun_iklan/update_action'),
		'id' => set_value('id', $row->id),
		'id_group' => set_value('id_group', $row->id_group),
		'akun' => set_value('akun', $row->akun),
	    );
            $this->load->view('akun_iklan/akun_iklan_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('akun_iklan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'id_group' => $this->input->post('id_group',TRUE),
		'akun' => $this->input->post('akun',TRUE),
	    );

            $this->Akun_iklan_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('akun_iklan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Akun_iklan_model->get_by_id($id);

        if ($row) {
            $this->Akun_iklan_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('akun_iklan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('akun_iklan'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_group', 'id group', 'trim|required');
	$this->form_validation->set_rules('akun', 'akun', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Akun_iklan.php */
/* Location: ./application/controllers/Akun_iklan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-17 08:19:16 */
/* http://harviacode.com */