<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Akun_retail_model extends CI_Model
{

    public $table = 'akun';
    public $id = 'id';
    public $id_toko = 'id_toko';
    public $kode = 'kode';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json($id_toko) {
        $this->datatables->select('id,id_toko,kode,akun');
        $this->datatables->from('akun');
        $this->datatables->where($this->id_toko, $id_toko);
        $this->datatables->add_column('action', anchor(site_url('outlet/akun_retail/read/$1'),'Read')." | ".anchor(site_url('outlet/akun_retail/update/$1'),'Update')." | ".anchor(site_url('outlet/akun_retail/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // datatables
    function json_produksi($id_toko) {
        $this->datatables->select('id,id_toko,kode,akun');
        $this->datatables->from('akun');
        $this->datatables->where($this->id_toko, $id_toko);
        $this->datatables->add_column('action', anchor(site_url('produksi/akun_retail/read/$1'),'Read')." | ".anchor(site_url('produksi/akun_retail/update/$1'),'Update')." | ".anchor(site_url('produksi/akun_retail/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get data by id toko
    function get_by_id_toko($id_toko)
    {
        $this->db->where($this->id_toko, $id_toko);
        $this->db->or_where($this->id_toko, 0);
        $this->db->order_by('kode', 'asc');
        return $this->db->get($this->table)->result();
    }

    // get data by sub kode
    function get_by_sub_kode($id_toko, $kode)
    {
        $panjang_kode = strlen($kode);
        $this->db->where($this->id_toko, $id_toko);
        $this->db->where('SUBSTRING(kode,1,'.$panjang_kode.')', $kode);
        $this->db->or_where($this->id_toko, 0);
        $this->db->where('SUBSTRING(kode,1,'.$panjang_kode.')', $kode);
        $this->db->order_by($this->kode, 'asc');
        return $this->db->get($this->table)->result();
    }

    // get sub kode baru
    function get_sub_kode_baru($id_toko, $kode)
    {
        $panjang_kode = strlen($kode);
        $exkode = explode(".", $kode);
        $row = $this->db->select("RIGHT(kode,2) AS kode")
                        ->from($this->table)
                        ->where($this->id_toko, $id_toko)
                        ->where("SUBSTRING(kode,1,".$panjang_kode.")", $kode)
                        ->where("LENGTH(kode)", $panjang_kode+3)
                        ->or_where($this->id_toko, 0)
                        ->where("SUBSTRING(kode,1,".$panjang_kode.")", $kode)
                        ->where("LENGTH(kode)", $panjang_kode+3)
                        ->order_by("kode", 'desc')
                        ->get()->row();
        return $row;
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
    	$this->db->or_like('id_toko', $q);
    	$this->db->or_like('kode', $q);
    	$this->db->or_like('akun', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_toko', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('akun', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Akun_retail_model.php */
/* Location: ./application/models/Akun_retail_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-08-12 04:14:04 */
/* http://harviacode.com */