<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Grafik extends AI_Admin
{
    function __construct()
    {
      parent::__construct();
    }

    public function index()
    {
      $bulan = $this->input->post('bulan', true);
      $tahun = $this->input->post('tahun', true);
      $jenis = $this->input->post('jenis', true)*1;

      if (empty($bulan)) {
        $bulan = date('m');
      }
      $bulan = sprintf('%02d', $bulan);
      if (empty($tahun)) {
        $tahun = date('Y');
      }
      $akhir_tgl = date('t', strtotime(date('01-'.$bulan.'-'.$tahun)));
      $s_per_01 = $tahun.'-'.$bulan.'-01';
      $s_per = $tahun.'-'.$bulan.'-'.$akhir_tgl;
      
      $data = array(
        'id_toko' => $this->userdata->id_toko,
        'nama_toko' => $this->userdata->nama_toko,
        'nama_user' => $this->userdata->email,
        'active_grafik' => 'active',
        'id_modul' => $this->userdata->id_modul,
        'nama_modul' => $this->userdata->nama_modul,
        'bulan' => $bulan,
        'tahun' => $tahun,
        'jenis' => $jenis,
        'akhir_tgl' => $akhir_tgl,
        'that' => $this,
        'data_pendapatan' => $this->db->where("SUBSTRING(a.kode,1,1)", "3")->order_by('a.kode', 'asc')->get("akun a"),
        'data_biaya' => $this->db->where("SUBSTRING(a.kode,1,1)", "4")->order_by('a.kode', 'asc')->get("akun a"),
      );
      $this->view('grafik/grafik_list',$data);
    }

    function get_saldo($tgl, $id_akun)
    {
      $this->db->select("j.id_akun, j.tgl, SUM(j.debet)-SUM(j.kredit) AS saldo");
      $this->db->from("jurnal j");
      $this->db->where('j.id_toko', $this->userdata->id_toko);
      $this->db->where("j.tgl", $tgl);
      $this->db->where("j.id_akun", $id_akun);
      return $this->db->get()->row();
    }

    function get_saldo_berjalan($tgl_awal, $tgl, $id_akun)
    {
      $exta = explode("-", $tgl_awal);
      $h_ta = $exta[0];
      $b_ta = $exta[1];
      $t_ta = $exta[2];
      $s_ta = $t_ta."-".$b_ta."-".$h_ta;

      $ext = explode("-", $tgl);
      $h_t = $ext[0];
      $b_t = $ext[1];
      $t_t = $ext[2];
      $s_t = $t_t."-".$b_t."-".$h_t;

      $this->db->select("j.id_akun, j.tgl, SUM(j.debet)-SUM(j.kredit) AS saldo");
      $this->db->from("jurnal j");
      $this->db->where('j.id_toko', $this->userdata->id_toko);
      $this->db->where("j.id_akun", $id_akun);
      $this->db->where("DATE(CONCAT(SUBSTRING(j.tgl,7,4),'-',SUBSTRING(j.tgl,4,2),'-',SUBSTRING(j.tgl,1,2))) BETWEEN '".$s_ta."' AND '".$s_t."' ");
      return $this->db->get()->row();
    }

    function get_saldo_berjalan_bulanan($bulan, $tahun, $id_akun)
    {

      $date = new DateTime('01-'.sprintf('%02d',$bulan).'-'.$tahun);
      $startDate = $date->format('Y-m-d');
      $endDate = $date->format('Y-m-t');

      $this->db->select("j.id_akun, j.tgl, SUM(j.debet)-SUM(j.kredit) AS saldo");
      $this->db->from("jurnal j");
      $this->db->where('j.id_toko', $this->userdata->id_toko);
      $this->db->where("j.id_akun", $id_akun);
      $this->db->where("DATE(CONCAT(SUBSTRING(j.tgl,7,4),'-',SUBSTRING(j.tgl,4,2),'-',SUBSTRING(j.tgl,1,2))) BETWEEN '".$startDate."' AND '".$endDate."' ");
      return $this->db->get()->row();
    }

}

/* End of file Grafik.php */
/* Location: ./application/controllers/Grafik.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-16 09:45:01 */
/* http://harviacode.com */