<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Gudang extends AI_Admin
{
    function __construct()
    {
        parent::__construct();
        $this->models('Gudang_model');
    }

    public function index()
    {
        $data = array(
            'active_gudang' => 'active',
        );
        $this->view('gudang/gudang_list', $data);
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Gudang_model->json();
    }

    public function read($id) 
    {
        $row = $this->Gudang_model->get_by_id($id);
        if ($row) {
            $data = array(
                'active_gudang' => 'active',
                'id' => $row->id,
                'nama_gudang' => $row->nama_gudang,
                'stok' => $row->stok,
            );
            $this->view('gudang/gudang_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/gudang'));
        }
    }

    public function create() 
    {
        $data = array(
            'active_gudang' => 'active',
            'button' => 'Create',
            'action' => site_url('admin/gudang/create_action'),
            'id' => set_value('id'),
            'nama_gudang' => set_value('nama_gudang'),
            'stok' => set_value('stok'),
        );
        $this->view('gudang/gudang_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'id_toko' => $this->userdata->id_toko,
                'nama_gudang' => $this->input->post('nama_gudang',TRUE),
                'stok' => $this->input->post('stok',TRUE),
            );

            $this->Gudang_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('admin/gudang'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Gudang_model->get_by_id($id);
        if ($row) {
            $data = array(
                'active_gudang' => 'active',
                'button' => 'Update',
                'action' => site_url('admin/gudang/update_action'),
                'id' => set_value('id', $row->id),
                'nama_gudang' => set_value('nama_gudang', $row->nama_gudang),
                'stok' => set_value('stok', $row->stok),
            );
            $this->view('gudang/gudang_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/gudang'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();
        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
                'nama_gudang' => $this->input->post('nama_gudang',TRUE),
                'stok' => $this->input->post('stok',TRUE),
            );
            $this->Gudang_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('admin/gudang'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Gudang_model->get_by_id($id);
        if ($row) {
            $this->Gudang_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('admin/gudang'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/gudang'));
        }
    }

    public function _rules() 
    {
        $this->form_validation->set_rules('nama_gudang', 'nama gudang', 'trim|required');
        // $this->form_validation->set_rules('stok', 'stok', 'trim|required');
        $this->form_validation->set_rules('id', 'id', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file gudang.php */
/* Location: ./application/controllers/gudang.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-20 04:02:20 */
/* http://harviacode.com */